### ISSUE TITLE
A3 version

### ISSUE THREAD

**Issue by glepretre** [alx741/vim_cheat_ball#3]
Hi,

First of all, thank you for sharing this! :smile: 

I just printed the pdf in A4 format, it's cute but a bit small. I tried printing it in A3 format but it's not scaling...

How could I print it in A3?

**Comment by alx741** [comment]
Hey,

Hmm seems like a lot of people find it too small, I'll try a multi-page version so it can be bigger and still be printed in A4 format.

**Comment by alx741** [comment]
Ok, now we have a larger version in the file _large.pdf_.

If you try it out, please let me know if is there anything wrong :)
